version: '3'

services:
  whatsapp-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - API_KEY=your-secret-api-key
      - LOG_LEVEL=info
      - WEBHOOK_URL=https://your-webhook-endpoint.com/whatsapp
      - WEBHOOK_ENABLED=false
    volumes:
      - whatsapp_auth:/usr/src/app/.wwebjs_auth
      - whatsapp_logs:/usr/src/app/logs
    restart: unless-stopped

volumes:
  whatsapp_auth:
  whatsapp_logs: