version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=whatsapp
      - MONGO_INITDB_ROOT_PASSWORD=whatsapp-password
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  whatsapp-api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - whatsapp_instances:/usr/src/app/instances
      - whatsapp_uploads:/usr/src/app/uploads
      - whatsapp_logs:/usr/src/app/logs
      - whatsapp_data:/usr/src/app/data
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
  whatsapp_instances:
  whatsapp_uploads:
  whatsapp_logs:
  whatsapp_data: