version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=whatsapp
      - MONGO_INITDB_ROOT_PASSWORD=whatsapp-password
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  whatsapp-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_PROVIDER=sqlite  # Можно изменить на mongodb
      - DATABASE_URL=mongodb://whatsapp:whatsapp-password@mongodb:27017/whatsapp-api?authSource=admin
      - SQLITE_DATABASE_URL=file:/usr/src/app/data/whatsapp-api.db
      - JWT_SECRET=your-jwt-secret-key-here
      - JWT_EXPIRATION=24h
      - LOG_LEVEL=info
      - MAX_FILE_SIZE=10485760
      - UPLOADS_DIR=./uploads
      - CORS_ORIGIN=*
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - whatsapp_instances:/usr/src/app/instances
      - whatsapp_uploads:/usr/src/app/uploads
      - whatsapp_logs:/usr/src/app/logs
      - whatsapp_data:/usr/src/app/data
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
  whatsapp_instances:
  whatsapp_uploads:
  whatsapp_logs:
  whatsapp_data: